Editor/Controllers/LayoutsController.cs
// <copyright file="LayoutsController.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Cms.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Web;
    using Cosmos.BlobService;
    using Cosmos.Cms.Common.Services.Configurations;
    using Cosmos.Cms.Data.Logic;
    using Cosmos.Common.Data;
    using Cosmos.Common.Models;
    using Cosmos.Common.Services;
    using HtmlAgilityPack;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.ModelBinding;
    using Microsoft.EntityFrameworkCore;
    using Sky.Cms.Models;
    using Sky.Cms.Services;
    using Sky.Editor.Data;
    using Sky.Editor.Data.Logic;
    using Sky.Editor.Models;
    using Sky.Editor.Models.GrapesJs;

    /// <summary>
    /// Layouts controller.
    /// </summary>
    // [ResponseCache(NoStore = true)]
    [Authorize(Roles = "Administrators, Editors")]
    public class LayoutsController : BaseController
    {
        private readonly ArticleEditLogic articleLogic;
        private readonly ApplicationDbContext dbContext;
        private readonly Uri blobPublicAbsoluteUrl;
        private readonly IViewRenderService viewRenderService;
        private readonly StorageContext storageContext;

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutsController"/> class.
        /// </summary>
        /// <param name="dbContext">Database context.</param>
        /// <param name="userManager">User manager.</param>
        /// <param name="articleLogic"><see cref="ArticleEditLogic">Article edit logic</see>.</param>
        /// <param name="options"><see cref="CosmosConfig">Cosmos configuration</see> options.</param>
        /// <param name="storageContext">Storage context.</param>
        /// <param name="viewRenderService">View rendering service.</param>
        public LayoutsController(
            ApplicationDbContext dbContext,
            UserManager<IdentityUser> userManager,
            ArticleEditLogic articleLogic,
            IEditorSettings options,
            StorageContext storageContext,
            IViewRenderService viewRenderService)
            : base(dbContext, userManager)
        {
            this.dbContext = dbContext;
            this.articleLogic = articleLogic;
            this.storageContext = storageContext;

            var htmlUtilities = new HtmlUtilities();

            if (htmlUtilities.IsAbsoluteUri(options.BlobPublicUrl))
            {
                blobPublicAbsoluteUrl = new Uri(options.BlobPublicUrl);
            }
            else
            {
                blobPublicAbsoluteUrl = new Uri($"{options.PublisherUrl.TrimEnd('/')}/{options.BlobPublicUrl.TrimStart('/')}");
            }

            this.viewRenderService = viewRenderService;
        }

        /// <summary>
        /// Gets a list of layouts.
        /// </summary>
        /// <returns>A list of layouts.</returns>
        public async Task<IActionResult> GetLayouts()
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var layouts = await dbContext.Layouts.ToListAsync();

            if (layouts.Any(l => l.Version.HasValue == false || l.Version == 0))
            {
                // Find the layout now published.
                var pub = layouts.FirstOrDefault(f => f.IsDefault);
                pub.Published = DateTimeOffset.UtcNow;
                pub.LastModified = DateTimeOffset.UtcNow;
                pub.Version = layouts.Count;

                // Increment the versions of the other layouts.
                var count = 1;
                foreach (var layout in layouts.Where(w => w.Id != pub.Id))
                {
                    layout.Published = null;
                    layout.LastModified = DateTimeOffset.UtcNow;
                    layout.Version = count;
                    count++;
                }

                await dbContext.SaveChangesAsync();
            }

            return Json(layouts.Select(s => new LayoutIndexViewModel ()
            {
                Id = s.Id,
                IsDefault = s.IsDefault,
                LayoutName = s.LayoutName,
                Notes = s.Notes,
                Version = s.Version.Value,
                LastModified = s.LastModified ?? DateTimeOffset.UtcNow,
                Published = s.Published
            }).OrderByDescending(o => o.Version).ToList());
        }

        /// <summary>
        /// Gets a list of layouts.
        /// </summary>
        /// <param name="sortOrder">Sort order either asc or desc (default is asc).</param>
        /// <param name="currentSort">Field to sort on.</param>
        /// <param name="pageNo">Page number to return.</param>
        /// <param name="pageSize">Number of records in each page.</param>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        public async Task<IActionResult> Index(string sortOrder = "asc", string currentSort = "LayoutName", int pageNo = 0, int pageSize = 10)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            ViewData["ShowCreateFirstLayout"] = !await dbContext.Layouts.CosmosAnyAsync();

            ViewData["ShowFirstPageBtn"] = !await dbContext.Articles.CosmosAnyAsync();

            ViewData["sortOrder"] = sortOrder;
            ViewData["currentSort"] = currentSort;
            ViewData["pageNo"] = pageNo;
            ViewData["pageSize"] = pageSize;

            var query = dbContext.Layouts.AsQueryable();

            ViewData["RowCount"] = await query.CountAsync();

            if (sortOrder == "desc")
            {
                if (!string.IsNullOrEmpty(currentSort))
                {
                    switch (currentSort)
                    {
                        case "LayoutName":
                            query = query.OrderByDescending(o => o.LayoutName);
                            break;
                    }
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(currentSort))
                {
                    switch (currentSort)
                    {
                        case "LayoutName":
                            query = query.OrderBy(o => o.LayoutName);
                            break;
                    }
                }
            }

            var model = query.Select(s => new LayoutIndexViewModel
            {
                Id = s.Id,
                IsDefault = s.IsDefault,
                LayoutName = s.LayoutName,
                Notes = s.Notes
            });

            return View(await model.Skip(pageNo * pageSize).Take(pageSize).ToListAsync());
        }

        /// <summary>
        /// Page returns a list of community layouts.
        /// </summary>
        /// <param name="sortOrder">Sort order either asc or desc (default is asc).</param>
        /// <param name="currentSort">Field to sort on.</param>
        /// <param name="pageNo">Page number to return.</param>
        /// <param name="pageSize">Number of records in each page.</param>
        /// <returns>Returns an <see cref="IActionResult"/>.</returns>
        public IActionResult CommunityLayouts(string sortOrder = "asc", string currentSort = "Name", int pageNo = 0, int pageSize = 10)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            ViewData["sortOrder"] = sortOrder;
            ViewData["currentSort"] = currentSort;
            ViewData["pageNo"] = pageNo;
            ViewData["pageSize"] = pageSize;

            var utilities = new LayoutUtilities();

            var query = utilities.CommunityCatalog.LayoutCatalog.AsQueryable();

            ViewData["RowCount"] = query.Count();

            if (sortOrder == "desc")
            {
                if (!string.IsNullOrEmpty(currentSort))
                {
                    switch (currentSort)
                    {
                        case "ArticleNumber":
                            query = query.OrderByDescending(o => o.License);
                            break;
                        case "Name":
                            query = query.OrderByDescending(o => o.Name);
                            break;
                        case "Description":
                            query = query.OrderByDescending(o => o.Description);
                            break;
                    }
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(currentSort))
                {
                    switch (currentSort)
                    {
                        case "ArticleNumber":
                            query = query.OrderBy(o => o.License);
                            break;
                        case "Name":
                            query = query.OrderBy(o => o.Name);
                            break;
                        case "Description":
                            query = query.OrderBy(o => o.Description);
                            break;
                    }
                }
            }

            return View(query.Skip(pageNo * pageSize).Take(pageSize).ToList());
        }

        /// <summary>
        /// Create a new layout.
        /// </summary>

Editor/Views/Layouts/EditCode.cshtml
@using Newtonsoft.Json
@model LayoutCodeViewModel
@{
    Layout = "_LayoutEditor";
    ViewData["Title"] = Model.EditorTitle;
    var fields = Model.EditorFields.ToArray();
    var aclass = "active";
    var readOnly = (bool?)ViewData["ReadOnly"] ?? false;
}

<style>

</style>

<nav class="code-tabs navbar">
    <ul class="nav nav-tabs " id="nav-tab">
        @{
            foreach (var field in fields)
            {
                    <li class="nav-item">
                        <a class="code-tabs nav-link @aclass" title="@field.ToolTip" data-bs-toggle="tooltip" data-bs-placement="bottom" data-ccms-fieldname="@field.FieldName" aria-current="page">@field.FieldName</a>
                    </li>
                aclass = "";
            }
        }
    </ul>
</nav>

<div id="editspace" class="m-editor-container"></div>

<form id="frmSave" asp-action="EditCode">
    <input type="hidden" asp-for="Id"/>
    <input type="hidden" asp-for="EditingField"/>
    <input type="hidden" asp-for="Head"/>
    <input type="hidden" asp-for="HtmlHeader"/>
    <input type="hidden" asp-for="FooterHtmlContent" />
    <input type="hidden" asp-for="EditorType" />
</form>

<script>
    var editor;
    var fieldId;
    var ccmsEditorIsLocked = false;
    const readOnly = @readOnly.ToString().ToLower();

    $("#frmSave").submit(function (e) {
        e.preventDefault();
        saveChanges(null, null);
    });

    // Example: var editFields = '[{"FieldId":"HeaderJavaScript","FieldName":"Header JavaScript","EditorMode":0},{"FieldId":"Content","FieldName":"Html Content","EditorMode":1},{"FieldId":"FooterJavaScript","FieldName":"Footer JavaScript","EditorMode":0}]';
    var editFields = @(Html.Raw(JsonConvert.SerializeObject(Model.EditorFields)));

    function saveExistingLoadNewEditor(id) {
        if (editor !== null && typeof editor !== "undefined") {
            $("#" + fieldId).val(editor.getValue());
        }
        createAndLoadEditor(id);
    }

    function closeEditor() {
        window.location.href = "@Url.Action("Index", "Layouts")";
    }

    //
    // Creates and loads a Monaco Editor.
    //
    function createAndLoadEditor(id) {
        if (editor !== null && typeof editor !== "undefined") {
            if (editor.getModel()) {
                editor.getModel().dispose();
            }
            $("#msgBox").html("Loading...");
            editor.dispose();
            editor = null;
        }

        fieldId = null;

        $("#EditingField").val(null);

        // Monaco AMD Editor  - https://microsoft.github.io/monaco-editor/
        require.config({ paths: { 'vs': window.location.origin + '/lib/monaco-editor/min/vs' } });

        //require.config({ paths: { vs: '/lib/node_modules/monaco-editor/dist' } }); // Emmet Abbr.
        require(['vs/editor/editor.main'],
            function () {
                fieldId = id;
                var fieldInfo = editFields.find(o => o.FieldName === id);
                fieldId = fieldInfo.FieldId;

                var mode = null;

                switch (fieldInfo.EditorMode) {
                    case 0:
                        mode = "javascript"
                        break;
                    case 1:
                        mode = "html"
                        break;
                    case 2:
                        mode = "css";
                        break;
                    default:
                        mode = "html"
                        break;
                }

                $("#EditingField").val(fieldId);
                var hiddenInput = $("#" + fieldId);
                var code = hiddenInput.val();
                emmetMonaco.emmetHTML(monaco);
                editor = monaco.editor.create(document.getElementById('editspace'),
                    {
                        language: mode,
                        theme: "vs-dark",
                        value: code
                    });

                $("#msgBox").html("");

                // Close loading spiner and display saved status
                $("#spinLoading").hide();
                $("#btnSavingStatus").show();
            });
    }

    // Save the changes for this editor
    function saveChanges(myModal) {

        if (readOnly) {
            return;
        }

        saving();

        if (typeof (myModel) !== "undefined" && myModel !== null) {
            myModal.hide();
        }
        // Saving publish date with time zone information
        savePublishDateTime();

        // Save title
        $("#Title").val($("#tbTitle").val());

        if (editor) {
            $("#" + fieldId).val(editor.getValue());
        }

        let model = {
            Id: $("#Id").val(),
            EditingField: $("#EditingField").val(),
            Head: encryptData($("#Head").val()),
            HtmlHeader: encryptData($("#HtmlHeader").val()),
            FooterHtmlContent: encryptData($("#FooterHtmlContent").val()),
            EditorType: $("#EditorType").val()
        }

        $.post("/Layouts/EditCode",
            model,
            function (response) {

                doneSaving();

                if (response.IsValid) {
                    if (next !== null && typeof next  === 'function') {
                        next();
                        next = null;
                    }
                    toastMsg("Successfully saved.");
                } else {
                    var errorMsg = "<h5>Error(s) detected while saving:</h5>";

                    // Invalid response.
                    $.each(response.Errors,
                        function (index, error) {
                            errorMsg = "<p>" + error.Key + "</p><ul>";
                            $.each(error.Errors,
                                function (index, innerError) {
                                    errorMsg = errorMsg + "<li>" + innerError.ErrorMessage + "</li>";
                                });
                            errorMsg = errorMsg + "</ul>";
                        });
                    $("#divErrorLog").html(errorMsg);
                    var errorModal = new bootstrap.Modal(document.getElementById('modalSavingError'));
                    errorModal.show();
                }
            }
        );
    }

    function btnSelectField(e) {
        fieldName = e.target.text();
        saveExistingLoadNewEditor(e.id);
    }

    $(document).ready(function () {
        
        $("body").addClass("cwps-editor-container");

        $("#liInsert").show();

        var fieldId = "@Model.EditingField";
        if (fieldId !== "") {
            var fieldInfo = editFields.find(o => o.FieldId === fieldId);
            createAndLoadEditor(fieldInfo.FieldName);
            // Refresh locks for everyone including self.
            setTimeout(function () {
                //ccmsSendSignal("NotifyRoomOfLock");
            }, 2000);
        }

        $("tblTitle").val("@Model.EditorTitle");

        $("[data-ccms-fieldname]").click(function (event) {
            var name = $(event.target).attr("data-ccms-fieldname");
            $("[data-ccms-fieldname]").removeClass("active");
            saveExistingLoadNewEditor(name);
            $(event.target).addClass("active");
        });

        $("#btnSaveAsDraft").hide();

        $("#btnSaveAsDraft").hide();

        $("#btnOpenLink").click(function (e) {
            if (openPickPageModal) {
                openPickPageModal();
            }
            else {
                alert("Could not find openPickPageModal().");
            }
        });

        $("#btnOpenInsertFileLink").click(function (e) {
            if (openInsertFileLinkModel) {
                openInsertFileLinkModel();
            }
            else {
                alert("Could not find openInsertFileLinkModel().");
            }
        });

        $("#btnOpenInsertImage").click(function (e) {
            if (openInsertImageModel) {
                openInsertImageModel();
            }
            else {
                alert("Could not find openInsertImageModel().");
            }
        });

        // Hide the navigation bar if in read-only mode.
        if (readOnly) {
            $("#navbarSupportedContent").hide();
        }
    });

    $(window).bind('keydown', function (event) {
        if (readOnly) {
            return;
        }

        if (event.ctrlKey || event.metaKey) {
            switch (String.fromCharCode(event.which).toLowerCase()) {
                case 's':
                    event.preventDefault();
                    $("#frmSave").submit();
                    break;
            }
        }
    });

    var timeout;

    $(window).bind('keyup', function (event) {

        if (readOnly) {
            return;
        }

        // Clear the timeout if it has already been set.
        // This will prevent the previous task from executing
        // if it has been less than <MILLISECONDS>
        clearTimeout(timeout);

        // Make a new timeout set to go off in 1000ms (1 second)
        timeout = setTimeout(function () {
            if (getAutoSave()) {
                $("#frmSave").submit();
            }
        }, 1500);
    });


    function openInsertFileLinkModel() {

        if (typeof editor === "undefined" || editor === null) {
            alert("Error: Could not open code editor.");
            return;
        }

        openSelectFileModal("file");

    }

    function openInsertImageModel() {

        if (typeof editor === "undefined" || editor === null) {
            alert("Error: Could not open code editor.");
            return;
        }

        openSelectFileModal("image");
    }

    function openPickPageModal() {

        if (typeof editor === "undefined" || editor === null) {
            alert("Error: Could not open code editor.");
            return;
        }

        $("#combobox").val("");

        pickPageModal.show();
    }

    function insertPageLink() {

        const inputLinkText = $("#inputLinkText").val();

        if (typeof (inputLinkText) === "undefined" || inputLinkText === null || inputLinkText === "") {
            $("#inputLinkTextError").show();
            return false;
        }

        pickPageModal.hide();

        const link = "<a href='/" + selectedAnchorData.url + "'>" + inputLinkText + "</a>";

        // insert text here
        editor.trigger('keyboard', 'type', { text: link });
    }

    function insertFileLink(path) {

        clearFileMgrPaths();

        const url = fileBaseUrl + "/" + path;

        const link = "<a href='" + url + "'>" + path + "</a>";

        // insert text here
        editor.trigger('keyboard', 'type', { text: link });
    }

    function insertImage(path) {

        clearFileMgrPaths();

        const url = fileBaseUrl + "/" + path;

        const image = "<img src='" + url + "' />";

        // insert text here
        editor.trigger('keyboard', 'type', { text: image });
    }
</script>

<script src="/lib/monaco-editor/min/vs/loader.js"></script>
<script src="/lib/emmet-monaco-es/dist/emmet-monaco.min.js"></script>

Editor/Views/Layouts/ExportLayout.cshtml
@using Sky.Cms.Services
@using Microsoft.Extensions.Options;
@using Cosmos.Cms.Common.Services.Configurations
@using Sky.Cms.Controllers
@model ArticleViewModel
@{
    Layout = "_LayoutPreview";
    ViewData["Title"] = Model.Title;
}

@Html.Raw(PageImportConstants.COSMOS_BODY_HEADER_START)
@Html.Raw(Model.Layout.HtmlHeader)
@Html.Raw(PageImportConstants.COSMOS_BODY_HEADER_END)

<!-- 
    ADD YOUR BODY CONTENT HERE 
    Note: This comment block can be removed.
-->

@Html.Raw(PageImportConstants.COSMOS_BODY_FOOTER_START)
@Html.Raw(Model.Layout.FooterHtmlContent)
@Html.Raw(PageImportConstants.COSMOS_BODY_FOOTER_END)

<!-- 
    ADD YOUR POST FOOTER/END OF BODY CONTENT HERE 
    Note: This comment block can be removed.
-->

Editor/Views/Layouts/Index.cshtml
@using Sky.Editor.Data.Logic
@using Microsoft.Extensions.Options;
@inject IEditorSettings options
@{
    ViewData["Title"] = "Site Design Version List";
    var showFirstPageBtn = (bool)ViewData["ShowFirstPageBtn"];
    var showCreateFirstLayout = (bool)ViewData["ShowCreateFirstLayout"];
}
<link href="~/lib/tabulator-tables/dist/css/tabulator_midnight.css" rel="stylesheet" />
<script src="~/lib/luxon/luxon.min.js"></script>
<script src="~/lib/tabulator-tables/dist/js/tabulator.min.js"></script>
<script src="~/js/clipboard.min.js"></script>
<style>
    .fs-small {
        font-size: 0.8em;
    }
</style>

<div class="pt-3">
    <div class="container">
        @if (showCreateFirstLayout)
        {
            <div class="row justify-content-center">
                <div class="col-md-10 text-light">
                    <h1>Site Design</h1>
                    <p>&quot;Designs&quot; provide a common functionality, look and feel across all pages on your website.</p>
                    <h4>Choose a pre-built website design (recommended)</h4>
                    <div class="ms-5 mb-5">
                        <p class="mb-3">These designs are ready for use and some are designed for non-technical users.  The is the recommened choice for most users.</p>
                        <a class="btn btn-sm btn-primary" asp-action="CommunityLayouts">Choose pre-built <i class="fa-solid fa-circle-arrow-right"></i></a>
                    </div>
                    <h4>Build your own website design (advanced)</h4>
                    <div class="ms-5 mb-3">
                        <p>If you are working with a web developer with at least basic HTML, CSS and JavaScript experience, you can choose to build a design from scratch that meets your specific needs.</p>
                        <a class="btn btn-small btn-primary" asp-action="Create">Choose custom <i class="fa-solid fa-circle-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col">
                    <h3 class="text-light">@ViewData["Title"]</h3>
                    @if (showFirstPageBtn && showCreateFirstLayout == false)
                    {
                        <a class="btn btn-sm btn-primary" title="Create website home page" href="/Editor/Create">Create Home Page <i class="fa-solid fa-circle-arrow-right"></i></a>
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group" role="group" aria-label="Page Actions">
                        <a class="btn btn-sm btn-primary" href="@Url.Action("Create")">New design</a>
                        <a class="btn btn-sm btn-secondary" title="Edit layout code." href="@Url.Action("EditCode")"><i class="fa-solid fa-code"></i> Code</a>
                        <a class="btn btn-sm btn-secondary" title="Edit with the designer tool." href="@Url.Action("Designer")"><i class="fa-solid fa-wand-magic-sparkles"></i> Design</a>
                        <a class="btn btn-sm btn-secondary" title="Edit design title and notes." href="@Url.Action("EditNotes")"><i class="fa-solid fa-pen-to-square"></i> Notes</a>
                        <a class="btn btn-sm btn-secondary" title="Import one of the community layouts." href="@Url.Action("CommunityLayouts")">Import design <i class="fa-solid fa-cloud-arrow-down"></i></a>
                        <a class="btn btn-sm btn-secondary" title="Return to page list" href="@Url.Action("Index", "Editor")">Page list <i class="fa-solid fa-circle-arrow-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="row cpws-table-pager-row-top">
                <div class="col-md-12 d-flex">
                   &nbsp;
                </div>
            </div>
            <div class="row bg-dark">
                <div class="col-md-12">
                    <div id="pagelist-table" class="table-dark"></div>
                </div>
            </div>
            <div class="row cpws-table-pager-row-bottom">
                <div class="col-md-12 d-flex justify-content-center">
                    &nbsp;
                </div>
            </div>
        }
    </div>
</div>

<script>

    const publisherUrl = "@options.PublisherUrl.TrimEnd('/')";
    const tblHeight = window.innerHeight - 200;
    let pageSize = Math.round(tblHeight / 50) + 1;

    function dateTime(cell, formatterParams, onRendered){
        //cell - the cell component
        //formatterParams - parameters set for the column
        //onRendered - function to call when the formatter has been rendered
        return getLocalTime(cell.getValue());
    }

    function dateFilterFunction(headerValue, rowValue, rowData, filterParams){
        if (rowValue === null || rowValue === "") {
            return false;
        }
        return headerValue === rowValue.split("T")[0]; //must return a boolean, true if it passes the filter.
    }

    const menuBar = function(cell, formatterParams){
        data = cell.getRow().getData();

        let html = "<div class='btn-group btn-group-sm' role='group' aria-label='Page actions.'>";
        html += "<btn onclick='viewCode(\"" + data.Id + "\")' title='View code in read-only mode.' class='btn btn-sm btn-secondary'><i class='fa-solid fa-file-code'></i></btn>";
        if (data.IsDefault === true){
            html += "<div title='Published design.' class='btn btn-sm btn-primary'><i class='fa-solid fa-circle-check'></i></div>";
        } else {
            html += "<div title='Published design.' class='btn btn-sm btn-secondary'><i class='fa-solid fa-xmark'></i></div>";
        }
        html += "<btn onclick='promote(\"" + data.Id + "\")' title='Create new version from this one.' class='btn btn-sm btn-secondary'><i class='fa-solid fa-square-caret-up'></i></btn>";
        html += "</div>";

        return html;
    };

    const pageTable = new Tabulator("#pagelist-table", {
        height:tblHeight + "px",
        pagination:true, //enable pagination
        paginationMode:"local", //enable local pagination
        paginationSize:pageSize, //optional parameter to request a certain number of rows per page
        persistence:{
            sort: true, //persist column sorting
            filter: true, //persist filters
            headerFilter: true, //persist header filters
            group: false, //persist row grouping
            page: true, //persist page
            columns: false, //persist columns
        },
        persistenceWriterFunc:function(id, type, data){
            //id - tables persistence id
            //type - type of data being persisted ("sort", "filter", "group", "page" or "columns")
            //data - array or object of data
            sessionStorage.setItem(id + "-" + type, JSON.stringify(data));
        },
        persistenceReaderFunc:function(id, type){
            //id - tables persistence id
            //type - type of data being persisted ("sort", "filter", "group", "page" or "columns")
            var data = sessionStorage.getItem(id + "-" + type);
            return data ? JSON.parse(data) : false;
        },
        layout:"fitColumns",
        ajaxURL:"@Url.Action("GetLayouts", "Layouts")", //ajax URL
        columns:[
                {title:"Id", field:"Id", visible: false },
                {title:"Notes", field:"Notes", visible: false },

                {title:"Actions", field:"IsDefault", formatter:menuBar, width:100, headerSort: false },

                {title:"Version", field:"Version", width: 25},

                {title:"Published",
                    field:"Published",
                    headerFilter:"date",
                    headerFilterFunc:dateFilterFunction,
                    width:180,
                    sorter:"datetime",
                    sorterParams:{
                        format:"iso" },
                    formatter:"datetime",
                    formatterParams:{
                        inputFormat:"iso",
                        outputFormat:"MM/dd/yyyy HH:mm:ss",
                        invalidPlaceholder:"(Invalid date)"
                    }
                },
                {title:"Modified",
                    field:"LastModified",
                    headerFilter:"date",
                    headerFilterFunc:dateFilterFunction,
                    width:180,
                    sorter:"datetime",
                    sorterParams:{
                        format:"iso" },
                    formatter:"datetime",
                    formatterParams:{
                        inputFormat:"iso",
                        outputFormat:"MM/dd/yyyy HH:mm:ss",
                        invalidPlaceholder:"(Invalid date)"
                    }
                },

                {title:"Name", field:"LayoutName", sorter:"string", headerFilter:"input" }
            ],
        });

    function viewCode(id) {
        const url = "@Url.Action("EditCode", "Layouts")/" + id;
        window.open(url, '_blank');
    }

    function promote(id) {
        $.get("@Url.Action("Promote", "Layouts")/" + id, function (data) {
            pageTable.setData();
        });
    }

    $(document).ready(function () {
        $("body").addClass("cwps-editor-container");
    });
</script>