Editor/Models/EditorViewModel.cs
// <copyright file="EditorViewModel.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Cms.Models
{
    /// <summary>
    /// Editor view model.
    /// </summary>
    public class EditorViewModel
    {
        /// <summary>
        /// Gets or sets file name.
        /// </summary>
        public string FieldName { get; set; }

        /// <summary>
        /// Gets or sets hTML content.
        /// </summary>
        public string Html { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether edit mode.
        /// </summary>
        public bool EditModeOn { get; set; }
    }
}

Editor/Models/NewHomeViewModel.cs
// <copyright file="NewHomeViewModel.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Cms.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// New home page view model.
    /// </summary>
    public class NewHomeViewModel
    {
        /// <summary>
        /// Gets or sets article ID.
        /// </summary>
        [Key]
        [Display(Name = "Article Key")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets article number.
        /// </summary>
        [Display(Name = "Article Number")]
        public int ArticleNumber { get; set; }

        /// <summary>
        /// Gets or sets article title.
        /// </summary>
        [Display(Name = "Page Title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether indicates to make this the new home page.
        /// </summary>
        [Display(Name = "Make this the new home page")]
        public bool IsNewHomePage { get; set; }

        /// <summary>
        /// Gets or sets article URL path.
        /// </summary>
        [Display(Name = "URL Path")]
        public string UrlPath { get; set; }
    }
}

Editor/Models/PreloadViewModel.cs
// <copyright file="PreloadViewModel.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Cms.Models
{
    /// <summary>
    /// Website preload options.
    /// </summary>
    public class PreloadViewModel
    {
        /// <summary>
        /// Gets or sets a value indicating whether preload CDN.
        /// </summary>
        public bool PreloadCdn { get; set; } = true;

        /// <summary>
        /// Gets or sets redis objects created.
        /// </summary>
        public int? PageCount { get; set; }

        /// <summary>
        /// Gets or sets number of editors involved with preload operation.
        /// </summary>
        public int EditorCount { get; set; } = 0;
    }
}

Editor/Models/ReservedPath.cs
// <copyright file="ReservedPath.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Cms.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Reserved path.
    /// </summary>
    /// <remarks>
    /// A reserved path prevents a page from being named that conflicts with a path.
    /// </remarks>
    public class ReservedPath
    {
        /// <summary>
        /// Gets or sets row ID.
        /// </summary>
        [Key]
        [Display(Name = "Id")]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Gets or sets reserved Path.
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Reserved Path")]
        public string Path { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether is required by Cosmos.
        /// </summary>
        [Display(Name = "Required by Cosmos?")]
        public bool CosmosRequired { get; set; } = false;

        /// <summary>
        /// Gets or sets reason by protected.
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Notes")]
        public string Notes { get; set; }
    }
}

Editor/Controllers/EditorController.cs
// <copyright file="EditorController.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Cms.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Web;
    using Cosmos.BlobService;
    using Cosmos.Common.Data;
    using Cosmos.Common.Data.Logic;
    using Cosmos.Common.Models;
    using Cosmos.Common.Services;
    using Sky.Editor.Controllers;
    using Sky.Editor.Data;
    using Sky.Editor.Data.Logic;
    using Sky.Editor.Models;
    using Sky.Editor.Models.GrapesJs;
    using Cosmos.Editor.Services;
    using HtmlAgilityPack;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.ModelBinding;
    using Microsoft.AspNetCore.SignalR;
    using Microsoft.Azure.Cosmos.Serialization.HybridRow;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Logging;
    using SendGrid.Helpers.Errors.Model;
    using Sky.Cms.Hubs;
    using Sky.Cms.Models;
    using Sky.Cms.Services;

    /// <summary>
    /// Editor controller.
    /// </summary>
    // [ResponseCache(NoStore = true)]
    [Authorize(Roles = "Reviewers, Administrators, Editors, Authors")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class EditorController : BaseController
    {
        private readonly ArticleEditLogic articleLogic;
        private readonly ApplicationDbContext dbContext;
        private readonly ILogger<EditorController> logger;
        private readonly IEditorSettings options;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;
        private readonly Uri blobPublicAbsoluteUrl;
        private readonly IViewRenderService viewRenderService;
        private readonly StorageContext storageContext;
        private readonly IWebHostEnvironment webHost;
        private readonly IHubContext<LiveEditorHub> hub;

        /// <summary>
        /// Initializes a new instance of the <see cref="EditorController"/> class.
        /// </summary>
        /// <param name="logger">ILogger to use.</param>
        /// <param name="dbContext">Database context.</param>
        /// <param name="userManager">User manager.</param>
        /// <param name="roleManager">Role manager.</param>
        /// <param name="articleLogic">Article logic.</param>
        /// <param name="options">Cosmos options.</param>
        /// <param name="viewRenderService">View rendering service.</param>
        /// <param name="storageContext">Storage context.</param>
        /// <param name="hub">Editor SignalR hub.</param>
        /// <param name="webHost">Host environment.</param>
        public EditorController(
            ILogger<EditorController> logger,
            ApplicationDbContext dbContext,
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            ArticleEditLogic articleLogic,
            IEditorSettings options,
            IViewRenderService viewRenderService,
            StorageContext storageContext,
            IHubContext<LiveEditorHub> hub,
            IWebHostEnvironment webHost)
            : base(dbContext, userManager)
        {
            this.logger = logger;
            this.dbContext = dbContext;
            this.options = options;
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.articleLogic = articleLogic;
            this.storageContext = storageContext;
            this.hub = hub;
            this.webHost = webHost;
            var htmlUtilities = new HtmlUtilities();

            if (htmlUtilities.IsAbsoluteUri(options.BlobPublicUrl))
            {
                blobPublicAbsoluteUrl = new Uri(options.BlobPublicUrl);
            }
            else
            {
                blobPublicAbsoluteUrl = new Uri($"{options.PublisherUrl.TrimEnd('/')}/{options.BlobPublicUrl.TrimStart('/')}");
            }

            this.viewRenderService = viewRenderService;

            // Ensure the required roles exist.
            SetupNewAdministrator.Ensure_Roles_Exists(roleManager).Wait();
        }

        /// <summary>
        /// Catalog of web pages on this website.
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        public async Task<IActionResult> Index()
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            ViewData["ShowFirstPageBtn"] = false; // Default unless changed below.

            if ((await dbContext.Articles.CountAsync()) == 0)
            {
                var template = await dbContext.Templates.Where(w => w.Title.ToLower().Contains("home page")).FirstOrDefaultAsync();

                if (template == null)
                {
                    ViewData["ShowFirstPageBtn"] = true;
                }
                else
                {
                    return View(viewName: "__NewHomePage", model:
                        new CreatePageViewModel()
                        {
                            TemplateId = template.Id,
                            Title = string.Empty,
                            ArticleNumber = 1,
                            Id = Guid.NewGuid()
                        });
                }
            }

            ViewData["HomePageArticleNumber"] = await dbContext.Pages.Where(f => f.UrlPath == "root").Select(s => s.ArticleNumber).FirstOrDefaultAsync();

            ViewData["ShowNotFoundBtn"] = !await dbContext.ArticleCatalog.Where(w => w.UrlPath == "not_found").CosmosAnyAsync();

            return View();
        }

        /// <summary>
        /// Loads the designer GUI.
        /// </summary>
        /// <param name="id">Article number.</param>
        /// <returns>View.</returns>
        public async Task<IActionResult> Designer(int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // Loads GrapeJS.
            ViewData["IsDesigner"] = true;

            var article = await GetArticleForEdit(id);

            if (article == null)
            {
                return NotFound();
            }

            var config = new DesignerConfig(await dbContext.Layouts.FirstOrDefaultAsync(f => f.IsDefault), article.ArticleNumber.ToString(), article.Title);
            var assets = await FileManagerController.GetImageAssetArray(storageContext, $"/pub/articles/{id}", string.Empty);
            if (assets != null)
            {
                config.ImageAssets.AddRange(assets);
            }

            ViewData["DesignerConfig"] = config;
            ViewData["Version"] = article.VersionNumber;

            ViewData["PageTitle"] = article.Title;
            ViewData["Published"] = null;
            ViewData["LastPubDateTime"] = await articleLogic.GetLastPublishedDate(id);

            var catalogEntry = await articleLogic.GetCatalogEntry(article);

            var designerUtils = new DesignerUtilities();
            var data = designerUtils.ExtractDesignerData(article.Content);

            return View(new ArticleDesignerDataViewModel
            {
                Id = article.Id,
                ArticleNumber = article.ArticleNumber,
                VersionNumber = article.VersionNumber,
                Title = article.Title,
                Published = null,
                ArticlePermissions = catalogEntry.ArticlePermissions,
                UrlPath = article.UrlPath,
                BannerImage = article.BannerImage,
                Updated = article.Updated,
                HtmlContent = data.HtmlContent,
                CssContent = data.CssContent,
            });
        }

        /// <summary>
        /// Save designer data.
        /// </summary>
        /// <param name="model">Designer post model.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        public async Task<IActionResult> Designer(ArticleDesignerDataViewModel model)
        {
            if (model == null)
            {
                return Json(new { success = false, message = "No data sent." });
            }

            model.HtmlContent = CryptoJsDecryption.Decrypt(model.HtmlContent);
            model.CssContent = CryptoJsDecryption.Decrypt(model.CssContent);

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // Check for nested editable regions.
            if (!NestedEditableRegionValidation.Validate(model.HtmlContent))
            {
                return BadRequest("Cannot have nested editable regions.");
            }

            // Next pull the original. This is a view model, not tracked by DbContext.
            var article = await articleLogic.GetArticleByArticleNumber(model.ArticleNumber, null);

            if (article == null)
            {
                return NotFound();
            }

            var designerUtils = new DesignerUtilities();
            var html = designerUtils.AssembleDesignerOutput(new DesignerDataViewModel() { CssContent = model.CssContent, HtmlContent = model.HtmlContent, Title = model.Title, Id = model.Id });

            try
            {
                var result = await articleLogic.SaveArticle(
                                    new ArticleViewModel()

Editor/Views/Editor/CcmsContent.cshtml
@using Microsoft.AspNetCore.Components
@model Cosmos.Common.Models.ArticleViewModel
@{
    Layout = null;
    ViewData["Title"] = Model.Title;

    var data = new ImportMapDefinition(
        new Dictionary<string, string>()
                                {
            { "ckeditor5", "/lib/ckeditor/ckeditor5.js" },
            { "ckeditor5/", "/lib/ckeditor/" },

            { "filelink", "/lib/cosmos/ckeditor/filelink/filelink.js" },
            { "filelink/", "/lib/cosmos/ckeditor/filelink/" },

            { "insertimage", "/lib/cosmos/ckeditor/insertimage/insertimage.js" },
            { "insertimage/", "/lib/cosmos/ckeditor/insertimage/" },

            { "pagelink", "/lib/cosmos/ckeditor/pagelink/pagelink.js" },
            { "pagelink/", "/lib/cosmos/ckeditor/pagelink/" },

            { "signalr", "/lib/cosmos/ckeditor/signalr/signalr.js" },
            { "signalr/", "/lib/cosmos/ckeditor/signalr/" },

            { "vscodeeditor", "/lib/cosmos/ckeditor/vscodeeditor/vscodeeditor.js" },
            { "vscodeeditor/", "/lib/cosmos/ckeditor/vscodeeditor/" },
                                },
        null,
        null);
}
<!DOCTYPE HTML>
<html lang="@Model.LanguageCode">
<head>
    <title>@Model.Title</title>
    <meta name="cwps-meta-path-title" content="@Model.Title" />
    <meta name="cwps-meta-path-url" content="@Model.UrlPath" />
    <meta name="cwps-meta-path-updated" content="@Model.Updated" />
    <style>
        figure.media {
            width: 640px;
        }

        .ck.ck-block-toolbar-button {
            transform: translateX( 30px ) translateY( -80px ) !important;
            background-color: white !important;
            border: 3px solid blue !important;
        }

        div.img-block:hover {
            border: 1px solid blue !important; /* Change border on hover */
        }

    </style>
    @Html.Raw(Model.Layout.Head)
    <link asp-append-version="true" rel="stylesheet" href="https://cdn.ckeditor.com/ckeditor5/44.1.0/ckeditor5.css" />
    <link asp-append-version="true" href="~/lib/filepond/filepond.css" rel="stylesheet" />
    @Html.Raw(Model.HeadJavaScript)
    @Html.Raw(JavaScriptSnippet.FullScript)
    <link asp-append-version="true" href="~/lib/cosmos/image-widget/image-widget.css" rel="stylesheet" />
    <script asp-append-version="true" src="~/lib/filepond-plugin-file-metadata/dist/filepond-plugin-file-metadata.js"></script>
    <script asp-append-version="true" src="~/lib/filepond/filepond.js"></script>
    <script asp-append-version="true" src="~/lib/cosmos/dublicator/componets/components.js"></script>
    <script asp-append-version="true" src="~/lib/cosmos/dublicator/dublicator.js"></script>
</head>
<body>
    @Html.Raw(Model.Layout.HtmlHeader)
    <div ccms-content-id="@Model.Id">
        @Html.Raw(Model.Content)
    </div>
    @Html.Raw(Model.Layout.FooterHtmlContent)
    @Html.Raw(Model.FooterJavaScript)
    @Html.AntiForgeryToken()
    <script type="importmap" asp-importmap="@data">
    </script>
    <link href="~/lib/cropperjs/cropper.min.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/lib/cropperjs/cropper.min.js" asp-append-version="true"></script>
    <script>

        // Create editors
        var ccms_editors = [];
        var ccms_editorIds = [];
        var focusedEditor;
        var unmoutCkBox;
        var articleNumber = @Model.ArticleNumber;
        var articleId = "@Model.Id";

        let autosaveTimeout = null;

        // Blur editors
        window.addEventListener('blur', function() {
            blurEditors();
        });

        // Blur editors
        function blurEditors() {
            // Make sure UI is closed for last editor that was active.
            const focused = document.querySelector('.ck-focused');
            if (focused) {
                focused.classList.remove('ck-focused');
            }
            const element = document.querySelector('.ck-balloon-panel_visible');
            if (element) {
                element.classList.remove('ck-balloon-panel_visible');
            }
        }

        // Close all dropdowns
        window.addEventListener("click", function () {
            parent.closeDropDowns();
        });

        window.addEventListener("keydown", (event) => {
            if (event.isComposing || event.keyCode === 229) {
                return;
            }

            // Handle CTRL-S to save changes
            if (event.ctrlKey || event.metaKey) {
                switch (String.fromCharCode(event.which).toLowerCase()) {
                    case 's':
                        event.preventDefault();
                        if (editor === null) {
                            parent.saveChanges();
                        } else {
                            parent.SaveEditorRegion(editor.getData(), editor.sourceElement.getAttribute("data-ccms-ceid"));
                        }
                        break;
                }
            }
        });

    </script>

    <script asp-append-version="true" src="~/lib/popper/umd/popper.min.js"></script>
    <script asp-append-version="true" src="~/lib/tippy/tippy.umd.min.js"></script>
    <script asp-append-version="true" type="module" src="~/lib/cosmos/ckeditor/ckeditor-widget.301.js"></script>
    <script asp-append-version="true" src="/lib/cosmos/image-widget/image-widget.js"></script>

    <script>
        const elements = document.querySelectorAll('[data-ccms-ceid]');
        elements.forEach(function (el, index) {
            el.setAttribute("data-tippy-content", "Editable.")
        });

        // NodeList
        let __cwps__toolTips = tippy(elements, {
            placement: "right-start",
            inlinePositioning: true,
        }); //data-ccms-ceid
        
        document.addEventListener('DOMContentLoaded', function () {
            const wineItems = document.querySelectorAll('.ccms-clone');
            wineItems.forEach(function (element) {
                Duplicator.create(element)
            });
        });
    </script>
</body>
</html>

Editor/Views/Editor/Clone.cshtml
@model DuplicateViewModel
@using Cosmos.Common.Models
@using Sky.Cms.Models
@{
    ViewData["Title"] = Model.Title;
    var original = (ArticleViewModel)ViewData["Original"];
}

<div class="cwps-editor-container container mt-5 pt-2">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h3 class="text-light">Clone Web Page</h3>
            <h5 class="text-light">Creating clone from: @ViewData["Title"]</h5>
        </div>
    </div>
    <hr />
    <div class="row justify-content-center">
        <div class="col-md-6">
            <p><a target="_blank" class="text-light" href="@Url.Action("Preview", "Home", new { Id = original.Id})" title="Click to open">Original page: &quot;@original.Title&quot; | Version: &quot;@original.VersionNumber&quot;</a></p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6 text-light">
            <form method="post" asp-action="Clone" asp-controller="Editor" class="g-3 needs-validation">
                @Html.AntiForgeryToken()
                <input id="Id" name="Id" type="hidden" value="@Model.Id" />
                @Html.HiddenFor(m => m.ArticleId)
                @Html.HiddenFor(m => m.ArticleVersion)
                @Html.HiddenFor(m => m.ParentPageTitle)
                <div class="mb-3">
                    <div asp-validation-summary=All class="text-danger"></div>
                </div>
                
                <div class="mb-3">
                    <label asp-for="Title" class="form-label"></label><span asp-validation-for="Title" class="text-danger"></span>
                    <input asp-for="Title" class="form-control" />
                    <p class="form-text">Note: Web page titles must be unique.</p>
                    
                </div>
                <div class="mb-3">
                    <label asp-for="Published" class="form-label"></label>
                    <span asp-validation-for="Published" class="text-danger"></span>
                    <input asp-for="Published" class="form-control" type="datetime-local" />
                    <p class="form-text">This is the date/time when this page is published.  Clear this to make this page not visible to the public.</p>
                </div>
                <div class="mb-3">
                    <a class="btn btn-secondary" asp-action="Versions" asp-route-id="@original.ArticleNumber">Cancel</a>
                    <button class="btn btn-primary" type="submit">Create Duplicate</button>
                </div>
            </form>
        </div>
    </div>
</div>

<partial name="_ValidationScriptsPartial" />

Editor/Views/Editor/Designer.cshtml
@using Newtonsoft.Json
@model Sky.Editor.Models.ArticleDesignerDataViewModel
@{
    Layout = "_LayoutEditor";
    ViewData["Title"] = Model.Title;
    var designerConfig = (Sky.Editor.Models.GrapesJs.DesignerConfig)ViewData["DesignerConfig"];
}

<form id="frmSave" asp-action="DesignerData" asp-controller="Editor" method="post">
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <input type="hidden" asp-for="Title" value="@Model.Title" />
    <input type="hidden" asp-for="HtmlContent" />
    <input type="hidden" asp-for="CssContent" />
    <input type="hidden" asp-for="SaveAsNewVersion" />
    <input type="hidden" asp-for="VersionNumber" />
    <input type="hidden" asp-for="ArticleNumber" />
    <input type="hidden" asp-for="Published" />
    <input type="hidden" asp-for="Updated" />
    <input type="hidden" asp-for="RoleList" />
    <input type="hidden" asp-for="UrlPath" />
    <input type="hidden" asp-for="IsValid" />
    <input type="hidden" asp-for="EditorType" />
    <input type="hidden" asp-for="UpdateExisting" />
    <input type="hidden" asp-for="BannerImage" />
</form>

<script>
    /*
      Cosmos Configuration.
    */
    var ccmsEditorIsLocked = false;
    // Current user
    const ccms_editor_userid = "@this.Context.User.Identity.Name";
    const hasModel = @((Model != null).ToString().ToLower());

    // This needs global scope, so using var
    var hasPermissionsSet = false;

    function closeEditor() {
        window.location.href = "@Url.Action("Index", "Editor", new { Model.Id })";
    }

    // Activated from _LayoutEditor.cshtml in multiple locations;
    async function saveChanges() {
        await editor.store();
        if (next !== null && typeof next  === 'function') {
            next();
            next = null;
        }
    }

    $("#frmSave").submit(function(event) {
        event.preventDefault(); // Prevents the default form submission
        saveChanges();
    });

    $(document).ready(function () {

        $('#tbPublished').prop("disabled", "true");

        $("#btnSaveAsDraft").hide();
        $("#btnOpenInsertImage").hide();
        $("#btnCcmsCodeEditor").show();

        $("#liInsert").show();
        $("#divTitleGroup").show();
        $("#spinLoading").hide();
        $("#btnSavingStatus").show();

        $("#divTitle").html("@Model.Title");
        $("#Title").val("@Model.Title");

        // Alter the default action of the save changes button
        // located on _LayoutEditor.cshtml.
        $("#modalBtnSaveFirst").on("click", function () {
            saveChanges();
        });

        if (hasModel && isReviewer === false && isAuthor === false && requiresAuthentication) {
            $(".perm").show();
        }

        checkDisplayLiveEditorButton("HtmlContent");
    });

    $(document).on("unload", function () {
        // Close filemanager window if opened
        if (typeof fileMgrPopup !== "undefined" && fileMgrPopup !== null && fileMgrPopup.location) {
            fileMgrPopup.close();
        }
    });

    /*

        GrapesJS Editor (Designer) Configuration

    */
    const cosmos__id = '@Model.ArticleNumber';

    const cosmos__designerAssetsEndPoint = "/pub/articles/" + cosmos__id;
    const cosmos__designerAssetsExclude = "";
    const cosmos__designerDataEndpoint = "/Editor/GetDesignerData";
    const cosmos__designerPostEndpoint = "/Editor/Designer";
    const cosmos__designerUploadEndpoint = "/FileManager/SimpleUpload?id=" + cosmos__id + "&entityType=articles&editorType=grapesjs";

    let grapesjs__canvas__styles = @Html.Raw(JsonConvert.SerializeObject(designerConfig.Styles));
    let grapesjs__canvas__scripts = @Html.Raw(JsonConvert.SerializeObject(designerConfig.Scripts));
    //let grapesjs__assets = preloadImages();

</script>

<partial name="_GrapesJsEditor" model="designerConfig" />

Editor/Views/Editor/Preload.cshtml
@addTagHelper *, Kendo.Mvc
@model PreloadViewModel

@{
    ViewData["Title"] = "Preload CDN";
}
<div class="cwps-editor-container pt-3">
<div class="container pt-2">
    <form asp-controller="Editor" asp-action="Preload" method="post">
        <div class="row">
            <div class="col">
                <h3>@ViewData["Title"]</h3>
                <hr />
                <p>
                    Use this tool to preload the Content Distribution Network (CDN) in use for this website.
                    This can improve website speed for web pages that are not viewed as much as others.
                </p>

                @if (Model.PageCount.HasValue)
                {
                    <h5>Preload Complete</h5>
                    <p>
                        Processed @Model.PageCount.Value page(s).
                    </p>
                }
                <div class="form-group">
                    <label for="PreloadCdn">Preload CDN</label>
                    <kendo-switch for="PreloadCdn" enabled="true" checked="true">
                        <messages checked="YES" unchecked="NO" />
                    </kendo-switch>
                </div>
                <p><span class="badge badge-warning">IMPORTANT!</span> For websites with many web pages, this process may take a few minutes to complete.</p>
                <br />
                <button id="btnPublish" class="btn btn-sm btn-success" type="submit">Preload Content</button>
            </div>
        </div>
    </form>
</div>
</div>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}