Editor/Controllers/Cosmos___SettingsController.cs
// <copyright file="Cosmos___SettingsController.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Editor.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using Cosmos.Common.Data;
    using Sky.Editor.Data.Logic;
    using Sky.Editor.Models;
    using Cosmos.Editor.Services;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Logging;

    /// <summary>
    /// The settings controller.
    /// </summary>
    [Authorize(Roles = "Administrators")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S101:Types should be named in PascalCase", Justification = "The URL must be unique and not have a changes of conflicting with user authored web page URLs.")]
    public class Cosmos___SettingsController : Controller
    {
        /// <summary>
        /// CDN group name constant.
        /// </summary>
        public static readonly string CDNGROUPNAME = "CDN";
        /// <summary>
        /// Editor settings group name.
        /// </summary>
        public static readonly string EDITORSETGROUPNAME = "EDITORSETTINGS";

        private readonly ApplicationDbContext dbContext;
        private readonly ILogger<Cosmos___SettingsController> logger;
        private readonly IEditorSettings settings;

        /// <summary>
        /// Initializes a new instance of the <see cref="Cosmos___SettingsController"/> class.
        /// </summary>
        /// <param name="dbContext">Sets the database context.</param>
        /// <param name="logger">Log service.</param>
        /// <param name="settings">Editor settings.</param>
        public Cosmos___SettingsController(
            ApplicationDbContext dbContext,
            ILogger<Cosmos___SettingsController> logger,
            IEditorSettings settings)
        {
            this.dbContext = dbContext;
            this.logger = logger;
            this.settings = settings;
        }

        /// <summary>
        /// Gets a CDN configuration.
        /// </summary>
        /// <param name="dbContext">Database context.</param>
        /// <returns>AzureCdnEndpoint.</returns>
        public static async Task<List<Setting>> GetCdnConfiguration(ApplicationDbContext dbContext)
        {
            var settings = await dbContext.Settings.Where(f => f.Group == CDNGROUPNAME).ToListAsync();

            if (settings.Any())
            {
                return settings;
            }

            return new List<Setting>();
        }

        /// <summary>
        /// Gets the index page.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Index()
        {
            if (true)
            {
                var model = ((EditorSettings)this.settings).GetEditorConfig();
                model.IsMultiTenantEditor = true; // This is set by environment variables and cannot be changed.
                return View(model);
            }
            else
            {
                var model = new EditorConfig((EditorSettings)settings);
                model.IsMultiTenantEditor = false; // This is set by environment variables and cannot be changed.
                return View(model);
            }
        }

        /// <summary>
        /// Updates the index page.
        /// </summary>
        /// <param name="model">Editor config model.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(EditorConfig model)
        {
            model.IsMultiTenantEditor = true; // This is set by environment variables and cannot be changed.
            //if (!ModelState.IsValid || !this.settings.IsMultiTenantEditor)
            //{
            //    return View(model);
            //}

            // Check if mode is static website, and if so, set the blob URL.
            if (model.StaticWebPages)
            {
                model.BlobPublicUrl = "/";
            }

            var allSettings = await dbContext.Settings.ToListAsync();
            var settings = allSettings.FirstOrDefault(f => f.Group == EDITORSETGROUPNAME);
            if (settings == null)
            {
                settings = new Setting
                {
                    Group = EDITORSETGROUPNAME,
                    Name = "EditorSettings",
                    Value = Newtonsoft.Json.JsonConvert.SerializeObject(model),
                    Description = "Settings used by the Cosmos Editor",
                };
                dbContext.Settings.Add(settings);
            }
            else
            {
                settings.Value = Newtonsoft.Json.JsonConvert.SerializeObject(model);
            }

            // Save the changes to the database.
            await dbContext.SaveChangesAsync();

            return View(model);
        }

        /// <summary>
        /// Gets the CDN configuration page.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public async Task<IActionResult> CDN()
        {
            ViewData["Operation"] = null;

            var settings = await GetCdnConfiguration(dbContext);

            var model = new CdnService(settings, logger, HttpContext);

            return View(model);
        }

        /// <summary>
        /// Updates the CDN configuration.
        /// </summary>
        /// <param name="config">The CDN end point configuration.</param>
        /// <returns>A <see cref="Task{TResult}"/> representing the result of the asynchronous operation.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CDN(CdnService config)
        {
            if (!ModelState.IsValid)
            {
                return View(config);
            }

            // If any of the Azure CDN fields are set, then all of them must be set.
            if (!string.IsNullOrEmpty(config.ResourceGroup)
                || !string.IsNullOrEmpty(config.ProfileName)
                || !string.IsNullOrEmpty(config.EndPointName)
                || config.SubscriptionId.HasValue)
            {
                if (string.IsNullOrEmpty(config.ResourceGroup))
                {
                    ModelState.AddModelError("ResourceGroup", "ERROR: Resource Group is required.");
                }

                if (string.IsNullOrEmpty(config.ProfileName))
                {
                    ModelState.AddModelError("ProfileName", "ERROR: Profile Name is required.");
                }

                if (string.IsNullOrEmpty(config.EndPointName))
                {
                    ModelState.AddModelError("EndPointName", "ERROR: End Point Name is required.");
                }

                if (config.SubscriptionId == null)
                {
                    ModelState.AddModelError("SubscriptionId", "ERROR: Subscription Id is required.");
                }

                if (!ModelState.IsValid)
                {
                    return View(config);
                }
            }

            if (!string.IsNullOrEmpty(config.SucuriApiKey) || !string.IsNullOrEmpty(config.SucuriApiSecret))
            {
                if (string.IsNullOrEmpty(config.SucuriApiKey))
                {
                    ModelState.AddModelError("SucuriApiKey", "ERROR Sucuri API Key is required.");
                }

                if (string.IsNullOrEmpty(config.SucuriApiSecret))
                {
                    ModelState.AddModelError("SucuriApiSecret", "ERROR Sucuri API Secret is required.");
                }

                if (!ModelState.IsValid)
                {
                    return View(config);
                }
            }

            var settings = await GetCdnConfiguration(dbContext);

            var profileName = settings.Find(f => f.Name == "ProfileName");
            if (profileName == null)
            {
                profileName = new Setting { Group = CDNGROUPNAME, Name = "ProfileName", Value = config.ProfileName };
                dbContext.Settings.Add(profileName);
            }
            else
            {
                profileName.Value = config.ProfileName;
            }

            var resourceGroupName = settings.Find(f => f.Name == "ResourceGroupName");
            if (resourceGroupName == null)
            {
                resourceGroupName = new Setting { Group = CDNGROUPNAME, Name = "ResourceGroupName", Value = config.ResourceGroup };
                dbContext.Settings.Add(resourceGroupName);
            }
            else
            {
                resourceGroupName.Value = config.ResourceGroup;
            }

            var isFrontDoor = settings.Find(f => f.Name == "IsFrontDoor");
            if (isFrontDoor == null)
            {
                isFrontDoor = new Setting { Group = CDNGROUPNAME, Name = "IsFrontDoor", Value = config.IsFrontDoor.ToString() };
                dbContext.Settings.Add(isFrontDoor);
            }
            else
            {
                isFrontDoor.Value = config.IsFrontDoor.ToString();
            }

            var subscriptionId = settings.Find(f => f.Name == "SubscriptionId");
            if (subscriptionId == null)
            {
                subscriptionId = new Setting { Group = CDNGROUPNAME, Name = "SubscriptionId", Value = config.SubscriptionId.ToString() };
                dbContext.Settings.Add(subscriptionId);
            }
            else
            {
                subscriptionId.Value = config.SubscriptionId.ToString();

Editor/Views/Cosmos___Settings/CDN.cshtml
@using Sky.Editor.Controllers
@using Cosmos.Editor.Services
@model CdnService

@{
    ViewData["Title"] = "Editor Setup";
    var testResult = (CdnResult)ViewData["Operation"];

    var openTop = string.IsNullOrEmpty(Model.EndPointName)
                  && string.IsNullOrEmpty(Model.ResourceGroup)
                  && !Model.SubscriptionId.HasValue
                  && string.IsNullOrEmpty(Model.ProfileName) ? "" : "show";
    var openBottom = string.IsNullOrEmpty(Model.SucuriApiKey)
                  && string.IsNullOrEmpty(Model.SucuriApiSecret) ? "" : "show";
}
<style>
    .text-danger {
        color: white !important;
        font-style: italic !important;
        font-weight: bold !important;
    }

    .accordion-button:not(.collapsed) {
        background-color: #dadada !important;
        color: black !important;
    }
</style>
<div class="pt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card pb-4 bg-dark text-light">
                <div class="card-header">
                    <h3 class="card-title">@ViewData["Title"]</h3>
                    <p>For help in setting up CDN integration, see our <a class="text-light" href="https://cosmos.moonrise.net/cdn_setup">documentation</a>.</p>
                    <a class="btn btn-sm btn-primary" asp-action="Index" asp-controller="Cosmos___Settings">Settings <i class="fa-solid fa-circle-arrow-right"></i></a>
                </div>
                <div class="card-body">
                    <form id="registerForm" method="post" asp-action="CDN" asp-controller="Cosmos___Settings">
                        <h2>Configuration Settings</h2>
                        <hr />
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="accordion bg-secondary text-light mb-5" id="frmAccordian" data-bs-theme="dark">
                            <div class="accordion-item  bg-secondary text-light " data-bs-theme="dark">
                                <h2 class="accordion-header bg-secondary text-light">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Microsoft CDN/Front Door
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse @openTop">
                                    <div class="accordion-body bg-secondary text-light ">

                                        <div class="mb-3 form-check">
                                            <input class="form-check-input" asp-for="IsFrontDoor" type="checkbox" class="form-check-input" />
                                            <label asp-for="IsFrontDoor" class="form-check-label"></label> (Check if this is Azure Front Door.)
                                            <span asp-validation-for="IsFrontDoor" class="text-danger"></span>
                                        </div>

                                        <div class="mb-3">
                                            <label asp-for="SubscriptionId"></label>
                                            <input asp-for="SubscriptionId" class="form-control" aria-required="true" />
                                            <span asp-validation-for="SubscriptionId" class="text-danger"></span>
                                        </div>

                                        <div class="mb-3">
                                            <label asp-for="ResourceGroup"></label>
                                            <input class="form-control" asp-for="ResourceGroup" aria-required="true" />
                                            <span asp-validation-for="ResourceGroup" class="text-danger"></span>
                                            <span class="text-muted">This is the resource group name where CDN or Front Door is installed.</span>
                                        </div>

                                        <div class="mb-3">
                                            <label asp-for="ProfileName"></label>
                                            <input class="form-control" asp-for="ProfileName" aria-required="true" />
                                            <span asp-validation-for="ProfileName" class="text-danger"></span>
                                        </div>

                                        <div class="mb-3">
                                            <label asp-for="EndPointName"></label>
                                            <input class="form-control" asp-for="EndPointName" aria-required="true" />
                                            <span asp-validation-for="EndPointName" class="text-danger"></span>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        Surcuri Firewall/CDN
                                    </button>
                                </h2>
                                <div id="collapseTwo" class="accordion-collapse collapse @openBottom">
                                    <div class="accordion-body bg-secondary text-light">

                                        <div class="mb-3">
                                            <label asp-for="SucuriApiKey"></label>
                                            <input class="form-control" asp-for="SucuriApiKey" aria-required="true" />
                                            <span asp-validation-for="SucuriApiKey" class="text-danger"></span>
                                        </div>

                                        <div class="mb-3">
                                            <label asp-for="SucuriApiSecret"></label>
                                            <input class="form-control" asp-for="SucuriApiSecret" aria-required="true" />
                                            <span asp-validation-for="SucuriApiSecret" class="text-danger"></span>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                        @if (@testResult != null)
                        {

                            @if (testResult.IsSuccessStatusCode)
                            {
                                <div class="alert alert-success" role="alert">
                                    <h2 class="alert-heading text-dark">Success</h2>
                                    <p>Your CDN settings have been saved and tested successfully.</p>
                                </div>
                            }
                            else
                            {
                                <div class="alert alert-warning" role="alert">
                                    <h2 class="alert-heading text-dark">Warning</h2>
                                    <p>There was an error testing your CDN settings. Please try again.</p>
                                    <p>
                                        @testResult.ReasonPhrase
                                    </p>
                                </div>
                            }

                        }

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div>

                        @if (testResult != null)
                        {
                            <div class="mb-3">
                                Message: @testResult.Message
                                @testResult.Status
                            </div>
                        }
                        </div>

                        <button id="btnSave" type="submit" class="btn btn-sm btn-primary">Save and test settings <i class="fa-solid fa-circle-arrow-right"></i></button>
                        <a asp-action="Index" class="btn btn-sm btn-secondary">Cancel <i class="fa-solid fa-circle-arrow-right"></i></a>
                        <a asp-action="Remove" asp-controller="Cosmos___Cdn" class="btn btn-primary">Remove <i class="fa-solid fa-circle-arrow-right"></i></a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("body").addClass("cwps-editor-container");
    });
</script>

<partial name="_ValidationScriptsPartial" />

Editor/Views/Cosmos___Settings/Index.cshtml
@using Sky.Editor.Controllers
@using Sky.Editor.Models
@using Cosmos.Editor.Services
@model EditorConfig

@{
    ViewData["Title"] = "Editor Setup";
}
<style>
    .text-danger {
        color: white !important;
        font-style: italic !important;
        font-weight: bold !important;
    }

    .accordion-button:not(.collapsed) {
        background-color: #dadada !important;
        color: black !important;
    }
</style>
<div class="pt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card pb-4 bg-dark text-light">
                <div class="card-header">
                    <h3 class="card-title">@ViewData["Title"]</h3>
                    <p>Website configuration settings.</p>
                    <a class="btn btn-sm btn-primary" asp-action="CDN" asp-controller="Cosmos___Settings">CDN Settings <i class="fa-solid fa-circle-arrow-right"></i></a>
                </div>
                <div class="card-body">
                    <form id="form1" method="post" asp-action="Index" asp-controller="Cosmos___Settings">
                        @Html.AntiForgeryToken()
                        <h2>Configuration Settings</h2>
                        <hr />
                        @if (!Model.IsMultiTenantEditor)
                        {
                            <span class="badge rounded-pill text-bg-primary mb-4">The following comes from the app service environment variables and cannot be edited here.</span>
                        }
                        <div class="mb-3 form-check" style="display:none;">
                            <input class="form-check-input" asp-for="AllowSetup" type="checkbox" class="form-check-input" readonly="@Model.IsMultiTenantEditor" />
                            <label asp-for="AllowSetup" class="form-check-label"></label>
                            <span class="text-muted">Enables setup mode for your website.</span>
                            <span asp-validation-for="AllowSetup" class="text-danger"></span>
                        </div>

                        <div class="mb-3 form-check">
                            <input class="form-check-input" asp-for="StaticWebPages" type="checkbox" class="form-check-input" readonly="@Model.IsMultiTenantEditor" />
                            <label asp-for="StaticWebPages" class="form-check-label"></label>
                            <span class="text-muted">Indicates if static mode is being used.</span>
                            <span asp-validation-for="StaticWebPages" class="text-danger"></span>
                        </div>

                        <div class="mb-3 form-check">
                            <input class="form-check-input" asp-for="CosmosRequiresAuthentication" type="checkbox" class="form-check-input" readonly="" />
                            <label asp-for="CosmosRequiresAuthentication" class="form-check-label"></label>
                            <span class="text-muted">For static mode this always is set to false.</span>
                            <span asp-validation-for="CosmosRequiresAuthentication" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="PublisherUrl"></label>
                            <input asp-for="PublisherUrl" class="form-control" aria-required="true" />
                            <span class="text-muted">This is your website's URL on the web.</span>
                            <span asp-validation-for="PublisherUrl" class="text-danger"></span>
                        </div>

                        <div class="mb-3" id="blobUrlBlock">
                            <label asp-for="BlobPublicUrl"></label>
                            <input class="form-control" asp-for="BlobPublicUrl" aria-required="true" />
                            <span asp-validation-for="BlobPublicUrl" class="text-danger"></span>
                            <span class="text-muted">This is the static asset storage URL for your website.</span>
                            <span asp-validation-for="BlobPublicUrl" class="text-danger"></span>
                        </div>

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        @if (@Model.IsMultiTenantEditor)
                        {
                            <button id="btnSave" type="submit" class="btn btn-sm btn-primary">Save settings <i class="fa-solid fa-circle-arrow-right"></i></button>
                            <a href="/" class="btn btn-sm btn-secondary">Done <i class="fa-solid fa-circle-arrow-right"></i></a>
                        }

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const isReadOnly = @((Model.IsMultiTenantEditor == false).ToString().ToLower());
    const isMultiTenant = @(Model.IsMultiTenantEditor.ToString().ToLower());

    $(document).ready(function () {
        $("body").addClass("cwps-editor-container");

        if (isReadOnly) {
            $('#form1 input').attr('readonly', 'readonly');
            $('#form1 input').prop('disabled', true);
        }

        if (isMultiTenant) {
            $('#blobUrlBlock').hide();
        }

        $('#StaticWebPages').on('click', function () {
            if ($(this).is(':checked')) {
                $('#blobUrlBlock').hide();
                $('#BlobPublicUrl').val('/');
            } else {
                $('#blobUrlBlock').show();
            }
        });
    });
</script>

<partial name="_ValidationScriptsPartial" />